// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sparkgrpc/commands.proto

/*
Package sparkgrpc is a generated protocol buffer package.

It is generated from these files:
	sparkgrpc/commands.proto

It has these top-level messages:
	CommandLineRequest
	CommandLineResponse
	RootCommand
	RootResponse
	ListRequest
	ListResponse
	FirmwareRequest
	FirmwareResponse
	Heartbeat
	AddressRequest
	AddressResponse
	ParameterRequest
	ParameterResponse
	ParameterListRequest
	ParameterListResponse
	SetpointRequest
	SetpointResponse
*/
package sparkgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandLineRequest struct {
	Stdin string `protobuf:"bytes,1,opt,name=stdin" json:"stdin,omitempty"`
}

func (m *CommandLineRequest) Reset()                    { *m = CommandLineRequest{} }
func (m *CommandLineRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandLineRequest) ProtoMessage()               {}
func (*CommandLineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandLineRequest) GetStdin() string {
	if m != nil {
		return m.Stdin
	}
	return ""
}

type CommandLineResponse struct {
	Stderr string `protobuf:"bytes,1,opt,name=stderr" json:"stderr,omitempty"`
	Stdout string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
}

func (m *CommandLineResponse) Reset()                    { *m = CommandLineResponse{} }
func (m *CommandLineResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandLineResponse) ProtoMessage()               {}
func (*CommandLineResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandLineResponse) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *CommandLineResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

type RootCommand struct {
	Device    string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	Keepalive bool   `protobuf:"varint,2,opt,name=keepalive" json:"keepalive,omitempty"`
	Help      bool   `protobuf:"varint,3,opt,name=help" json:"help,omitempty"`
}

func (m *RootCommand) Reset()                    { *m = RootCommand{} }
func (m *RootCommand) String() string            { return proto.CompactTextString(m) }
func (*RootCommand) ProtoMessage()               {}
func (*RootCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RootCommand) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *RootCommand) GetKeepalive() bool {
	if m != nil {
		return m.Keepalive
	}
	return false
}

func (m *RootCommand) GetHelp() bool {
	if m != nil {
		return m.Help
	}
	return false
}

type RootResponse struct {
	HelpString string `protobuf:"bytes,1,opt,name=helpString" json:"helpString,omitempty"`
	Error      string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *RootResponse) Reset()                    { *m = RootResponse{} }
func (m *RootResponse) String() string            { return proto.CompactTextString(m) }
func (*RootResponse) ProtoMessage()               {}
func (*RootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RootResponse) GetHelpString() string {
	if m != nil {
		return m.HelpString
	}
	return ""
}

func (m *RootResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListRequest struct {
	Root *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	All  bool         `protobuf:"varint,2,opt,name=all" json:"all,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ListRequest) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

type ListResponse struct {
	DeviceList    []string      `protobuf:"bytes,1,rep,name=deviceList" json:"deviceList,omitempty"`
	DeviceDetails []string      `protobuf:"bytes,2,rep,name=deviceDetails" json:"deviceDetails,omitempty"`
	Root          *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListResponse) GetDeviceList() []string {
	if m != nil {
		return m.DeviceList
	}
	return nil
}

func (m *ListResponse) GetDeviceDetails() []string {
	if m != nil {
		return m.DeviceDetails
	}
	return nil
}

func (m *ListResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

type FirmwareRequest struct {
	Root     *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	Filename string       `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
}

func (m *FirmwareRequest) Reset()                    { *m = FirmwareRequest{} }
func (m *FirmwareRequest) String() string            { return proto.CompactTextString(m) }
func (*FirmwareRequest) ProtoMessage()               {}
func (*FirmwareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FirmwareRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *FirmwareRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type FirmwareResponse struct {
	Version string        `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Root    *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *FirmwareResponse) Reset()                    { *m = FirmwareResponse{} }
func (m *FirmwareResponse) String() string            { return proto.CompactTextString(m) }
func (*FirmwareResponse) ProtoMessage()               {}
func (*FirmwareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FirmwareResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *FirmwareResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

type Heartbeat struct {
	Root   *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	Enable bool         `protobuf:"varint,2,opt,name=enable" json:"enable,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Heartbeat) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Heartbeat) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type AddressRequest struct {
	Root    *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	Address uint32       `protobuf:"varint,2,opt,name=address" json:"address,omitempty"`
}

func (m *AddressRequest) Reset()                    { *m = AddressRequest{} }
func (m *AddressRequest) String() string            { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()               {}
func (*AddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AddressRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *AddressRequest) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

type AddressResponse struct {
	CurrentAddress  uint32        `protobuf:"varint,1,opt,name=currentAddress" json:"currentAddress,omitempty"`
	PreviousAddress uint32        `protobuf:"varint,2,opt,name=previousAddress" json:"previousAddress,omitempty"`
	Root            *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *AddressResponse) Reset()                    { *m = AddressResponse{} }
func (m *AddressResponse) String() string            { return proto.CompactTextString(m) }
func (*AddressResponse) ProtoMessage()               {}
func (*AddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddressResponse) GetCurrentAddress() uint32 {
	if m != nil {
		return m.CurrentAddress
	}
	return 0
}

func (m *AddressResponse) GetPreviousAddress() uint32 {
	if m != nil {
		return m.PreviousAddress
	}
	return 0
}

func (m *AddressResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

type ParameterRequest struct {
	Root      *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	Parameter string       `protobuf:"bytes,2,opt,name=parameter" json:"parameter,omitempty"`
	Value     []byte       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ParameterRequest) Reset()                    { *m = ParameterRequest{} }
func (m *ParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*ParameterRequest) ProtoMessage()               {}
func (*ParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ParameterRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ParameterRequest) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *ParameterRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ParameterResponse struct {
	OldParameter string        `protobuf:"bytes,1,opt,name=oldParameter" json:"oldParameter,omitempty"`
	NewParameter string        `protobuf:"bytes,2,opt,name=newParameter" json:"newParameter,omitempty"`
	Root         *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *ParameterResponse) Reset()                    { *m = ParameterResponse{} }
func (m *ParameterResponse) String() string            { return proto.CompactTextString(m) }
func (*ParameterResponse) ProtoMessage()               {}
func (*ParameterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ParameterResponse) GetOldParameter() string {
	if m != nil {
		return m.OldParameter
	}
	return ""
}

func (m *ParameterResponse) GetNewParameter() string {
	if m != nil {
		return m.NewParameter
	}
	return ""
}

func (m *ParameterResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

type ParameterListRequest struct {
	Root *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
}

func (m *ParameterListRequest) Reset()                    { *m = ParameterListRequest{} }
func (m *ParameterListRequest) String() string            { return proto.CompactTextString(m) }
func (*ParameterListRequest) ProtoMessage()               {}
func (*ParameterListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ParameterListRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

type ParameterListResponse struct {
	Parameter []string      `protobuf:"bytes,1,rep,name=parameter" json:"parameter,omitempty"`
	Root      *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *ParameterListResponse) Reset()                    { *m = ParameterListResponse{} }
func (m *ParameterListResponse) String() string            { return proto.CompactTextString(m) }
func (*ParameterListResponse) ProtoMessage()               {}
func (*ParameterListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ParameterListResponse) GetParameter() []string {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *ParameterListResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

type SetpointRequest struct {
	Root     *RootCommand `protobuf:"bytes,1,opt,name=root" json:"root,omitempty"`
	Setpoint float32      `protobuf:"fixed32,2,opt,name=setpoint" json:"setpoint,omitempty"`
}

func (m *SetpointRequest) Reset()                    { *m = SetpointRequest{} }
func (m *SetpointRequest) String() string            { return proto.CompactTextString(m) }
func (*SetpointRequest) ProtoMessage()               {}
func (*SetpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SetpointRequest) GetRoot() *RootCommand {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *SetpointRequest) GetSetpoint() float32 {
	if m != nil {
		return m.Setpoint
	}
	return 0
}

type SetpointResponse struct {
	Setpoint  float32       `protobuf:"fixed32,1,opt,name=setpoint" json:"setpoint,omitempty"`
	IsRunning bool          `protobuf:"varint,2,opt,name=isRunning" json:"isRunning,omitempty"`
	Root      *RootResponse `protobuf:"bytes,3,opt,name=root" json:"root,omitempty"`
}

func (m *SetpointResponse) Reset()                    { *m = SetpointResponse{} }
func (m *SetpointResponse) String() string            { return proto.CompactTextString(m) }
func (*SetpointResponse) ProtoMessage()               {}
func (*SetpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SetpointResponse) GetSetpoint() float32 {
	if m != nil {
		return m.Setpoint
	}
	return 0
}

func (m *SetpointResponse) GetIsRunning() bool {
	if m != nil {
		return m.IsRunning
	}
	return false
}

func (m *SetpointResponse) GetRoot() *RootResponse {
	if m != nil {
		return m.Root
	}
	return nil
}

func init() {
	proto.RegisterType((*CommandLineRequest)(nil), "sparkgrpc.commandLineRequest")
	proto.RegisterType((*CommandLineResponse)(nil), "sparkgrpc.commandLineResponse")
	proto.RegisterType((*RootCommand)(nil), "sparkgrpc.rootCommand")
	proto.RegisterType((*RootResponse)(nil), "sparkgrpc.rootResponse")
	proto.RegisterType((*ListRequest)(nil), "sparkgrpc.listRequest")
	proto.RegisterType((*ListResponse)(nil), "sparkgrpc.listResponse")
	proto.RegisterType((*FirmwareRequest)(nil), "sparkgrpc.firmwareRequest")
	proto.RegisterType((*FirmwareResponse)(nil), "sparkgrpc.firmwareResponse")
	proto.RegisterType((*Heartbeat)(nil), "sparkgrpc.heartbeat")
	proto.RegisterType((*AddressRequest)(nil), "sparkgrpc.addressRequest")
	proto.RegisterType((*AddressResponse)(nil), "sparkgrpc.addressResponse")
	proto.RegisterType((*ParameterRequest)(nil), "sparkgrpc.parameterRequest")
	proto.RegisterType((*ParameterResponse)(nil), "sparkgrpc.parameterResponse")
	proto.RegisterType((*ParameterListRequest)(nil), "sparkgrpc.parameterListRequest")
	proto.RegisterType((*ParameterListResponse)(nil), "sparkgrpc.parameterListResponse")
	proto.RegisterType((*SetpointRequest)(nil), "sparkgrpc.setpointRequest")
	proto.RegisterType((*SetpointResponse)(nil), "sparkgrpc.setpointResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sparkusb service

type SparkusbClient interface {
	Connect(ctx context.Context, in *RootCommand, opts ...grpc.CallOption) (*RootResponse, error)
	Disconnect(ctx context.Context, in *RootCommand, opts ...grpc.CallOption) (*RootResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// rpc Firmware(firmwareRequest) returns (firmwareResponse) {}
	Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*RootResponse, error)
	CommandLine(ctx context.Context, in *CommandLineRequest, opts ...grpc.CallOption) (*CommandLineResponse, error)
}

type sparkusbClient struct {
	cc *grpc.ClientConn
}

func NewSparkusbClient(cc *grpc.ClientConn) SparkusbClient {
	return &sparkusbClient{cc}
}

func (c *sparkusbClient) Connect(ctx context.Context, in *RootCommand, opts ...grpc.CallOption) (*RootResponse, error) {
	out := new(RootResponse)
	err := grpc.Invoke(ctx, "/sparkgrpc.sparkusb/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkusbClient) Disconnect(ctx context.Context, in *RootCommand, opts ...grpc.CallOption) (*RootResponse, error) {
	out := new(RootResponse)
	err := grpc.Invoke(ctx, "/sparkgrpc.sparkusb/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkusbClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/sparkgrpc.sparkusb/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkusbClient) Heartbeat(ctx context.Context, in *Heartbeat, opts ...grpc.CallOption) (*RootResponse, error) {
	out := new(RootResponse)
	err := grpc.Invoke(ctx, "/sparkgrpc.sparkusb/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkusbClient) CommandLine(ctx context.Context, in *CommandLineRequest, opts ...grpc.CallOption) (*CommandLineResponse, error) {
	out := new(CommandLineResponse)
	err := grpc.Invoke(ctx, "/sparkgrpc.sparkusb/CommandLine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sparkusb service

type SparkusbServer interface {
	Connect(context.Context, *RootCommand) (*RootResponse, error)
	Disconnect(context.Context, *RootCommand) (*RootResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	// rpc Firmware(firmwareRequest) returns (firmwareResponse) {}
	Heartbeat(context.Context, *Heartbeat) (*RootResponse, error)
	CommandLine(context.Context, *CommandLineRequest) (*CommandLineResponse, error)
}

func RegisterSparkusbServer(s *grpc.Server, srv SparkusbServer) {
	s.RegisterService(&_Sparkusb_serviceDesc, srv)
}

func _Sparkusb_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkusbServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkgrpc.sparkusb/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkusbServer).Connect(ctx, req.(*RootCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sparkusb_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkusbServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkgrpc.sparkusb/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkusbServer).Disconnect(ctx, req.(*RootCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sparkusb_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkusbServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkgrpc.sparkusb/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkusbServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sparkusb_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Heartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkusbServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkgrpc.sparkusb/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkusbServer).Heartbeat(ctx, req.(*Heartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sparkusb_CommandLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkusbServer).CommandLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkgrpc.sparkusb/CommandLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkusbServer).CommandLine(ctx, req.(*CommandLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sparkusb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sparkgrpc.sparkusb",
	HandlerType: (*SparkusbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Sparkusb_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Sparkusb_Disconnect_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Sparkusb_List_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Sparkusb_Heartbeat_Handler,
		},
		{
			MethodName: "CommandLine",
			Handler:    _Sparkusb_CommandLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sparkgrpc/commands.proto",
}

func init() { proto.RegisterFile("sparkgrpc/commands.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x6b, 0x14, 0x31,
	0x10, 0xee, 0xde, 0xd5, 0xb6, 0x37, 0x77, 0x6d, 0xcf, 0x58, 0xeb, 0x52, 0x6a, 0x91, 0x20, 0x52,
	0x2a, 0x54, 0xa8, 0x4f, 0x42, 0x41, 0x6a, 0x2b, 0x08, 0x16, 0x2d, 0x2b, 0x28, 0x7d, 0xcc, 0xdd,
	0x4e, 0xdb, 0xd0, 0xbd, 0x64, 0x4d, 0xb2, 0x57, 0x7c, 0xf4, 0xcd, 0x47, 0x7f, 0x9b, 0xbf, 0x48,
	0x92, 0xcd, 0x66, 0x77, 0x4f, 0x2a, 0xdc, 0xbd, 0xed, 0x7c, 0x99, 0xf9, 0xf2, 0x7d, 0xb3, 0xc9,
	0x04, 0x62, 0x9d, 0x33, 0x75, 0x7b, 0xad, 0xf2, 0xf1, 0xab, 0xb1, 0x9c, 0x4c, 0x98, 0x48, 0xf5,
	0x61, 0xae, 0xa4, 0x91, 0xa4, 0x17, 0x56, 0xe8, 0x01, 0x10, 0xbf, 0x78, 0xce, 0x05, 0x26, 0xf8,
	0xbd, 0x40, 0x6d, 0xc8, 0x16, 0x3c, 0xd0, 0x26, 0xe5, 0x22, 0x8e, 0x9e, 0x45, 0xfb, 0xbd, 0xa4,
	0x0c, 0xe8, 0x7b, 0x78, 0xd4, 0xca, 0xd5, 0xb9, 0x14, 0x1a, 0xc9, 0x36, 0xac, 0x68, 0x93, 0xa2,
	0x52, 0x3e, 0xdb, 0x47, 0x1e, 0x97, 0x85, 0x89, 0x3b, 0x01, 0x97, 0x85, 0xa1, 0xdf, 0xa0, 0xaf,
	0xa4, 0x34, 0xa7, 0x25, 0x95, 0x4d, 0x4b, 0x71, 0xca, 0xc7, 0x58, 0x95, 0x97, 0x11, 0xd9, 0x85,
	0xde, 0x2d, 0x62, 0xce, 0x32, 0x3e, 0x45, 0xc7, 0xb0, 0x96, 0xd4, 0x00, 0x21, 0xb0, 0x7c, 0x83,
	0x59, 0x1e, 0x77, 0xdd, 0x82, 0xfb, 0xa6, 0x67, 0x30, 0xb0, 0xc4, 0x41, 0xd8, 0x1e, 0x80, 0xc5,
	0xbf, 0x18, 0xc5, 0xc5, 0xb5, 0x67, 0x6f, 0x20, 0xd6, 0x25, 0x2a, 0x25, 0x95, 0xd7, 0x57, 0x06,
	0xf4, 0x23, 0xf4, 0x33, 0xae, 0x4d, 0xd5, 0x8a, 0x03, 0x58, 0xb6, 0xa4, 0xae, 0xbc, 0x7f, 0xb4,
	0x7d, 0x18, 0x5a, 0x77, 0xd8, 0x30, 0x91, 0xb8, 0x1c, 0x32, 0x84, 0x2e, 0xcb, 0x32, 0x2f, 0xd6,
	0x7e, 0xd2, 0x9f, 0x11, 0x0c, 0x4a, 0xb6, 0x5a, 0x53, 0xe9, 0xef, 0x9c, 0x6b, 0x4b, 0xda, 0xb5,
	0x9a, 0x6a, 0x84, 0x3c, 0x87, 0xf5, 0x32, 0x3a, 0x43, 0xc3, 0x78, 0xa6, 0xe3, 0x8e, 0x4b, 0x69,
	0x83, 0xe4, 0xa5, 0x17, 0xd5, 0x75, 0xa2, 0x9e, 0xcc, 0x88, 0xaa, 0x36, 0x2b, 0x55, 0xd1, 0x4b,
	0xd8, 0xbc, 0xe2, 0x6a, 0x72, 0xc7, 0x14, 0x2e, 0x62, 0x6a, 0x07, 0xd6, 0xae, 0x78, 0x86, 0x82,
	0x4d, 0xd0, 0x37, 0x2a, 0xc4, 0xf4, 0x12, 0x86, 0x35, 0xb5, 0x77, 0x18, 0xc3, 0xea, 0x14, 0x95,
	0xe6, 0xb2, 0x3a, 0x3d, 0x55, 0x38, 0x9f, 0xea, 0xcf, 0xd0, 0xbb, 0x41, 0xa6, 0xcc, 0x08, 0xd9,
	0x7c, 0x7a, 0xb7, 0x61, 0x05, 0x05, 0x1b, 0x65, 0xd5, 0xa1, 0xf1, 0x11, 0xfd, 0x0a, 0x1b, 0x2c,
	0x4d, 0x15, 0x6a, 0xbd, 0x48, 0x17, 0x62, 0x58, 0xf5, 0xd5, 0x8e, 0x76, 0x3d, 0xa9, 0x42, 0xfa,
	0x3b, 0x82, 0xcd, 0x40, 0xec, 0x7b, 0xf0, 0x02, 0x36, 0xc6, 0x85, 0x52, 0x28, 0xcc, 0x89, 0x2f,
	0x8a, 0x5c, 0xd1, 0x0c, 0x4a, 0xf6, 0x61, 0x33, 0x57, 0x38, 0xe5, 0xb2, 0xd0, 0x27, 0x2d, 0xf6,
	0x59, 0x78, 0xbe, 0xde, 0x29, 0x18, 0xe6, 0x4c, 0xb1, 0x09, 0x1a, 0x54, 0x8b, 0x98, 0xdd, 0x85,
	0x5e, 0xa8, 0xf7, 0xff, 0xbc, 0x06, 0xec, 0xb5, 0x99, 0xb2, 0xac, 0x40, 0xa7, 0x65, 0x90, 0x94,
	0x01, 0xfd, 0x15, 0xc1, 0xc3, 0xc6, 0xa6, 0xbe, 0x11, 0x14, 0x06, 0x32, 0x4b, 0x2f, 0x02, 0x59,
	0x79, 0x22, 0x5a, 0x98, 0xcd, 0x11, 0x78, 0x77, 0x31, 0xb3, 0x61, 0x0b, 0x9b, 0xcf, 0xfe, 0x3b,
	0xd8, 0x0a, 0x4a, 0xce, 0x17, 0xbb, 0xca, 0x74, 0x04, 0x8f, 0x67, 0x38, 0xbc, 0xa3, 0x56, 0x6f,
	0xca, 0xfb, 0xdb, 0xe8, 0xcd, 0xbc, 0x17, 0x53, 0xa3, 0xc9, 0x25, 0x17, 0x66, 0xc1, 0x8b, 0x59,
	0x95, 0xbb, 0x9e, 0x75, 0x92, 0x10, 0xd3, 0x1f, 0x30, 0xac, 0xa9, 0xbd, 0xf2, 0x66, 0x7e, 0xd4,
	0xce, 0xb7, 0xae, 0xb8, 0x4e, 0x0a, 0x21, 0xec, 0xa4, 0xf4, 0xc3, 0x36, 0x00, 0x73, 0xb9, 0x3a,
	0xfa, 0xd3, 0x81, 0x35, 0x97, 0x50, 0xe8, 0x11, 0x39, 0x86, 0xd5, 0x53, 0x29, 0x04, 0x8e, 0x0d,
	0xb9, 0xc7, 0xcc, 0xce, 0x7d, 0x74, 0x74, 0x89, 0xbc, 0x05, 0x38, 0xe3, 0x7a, 0xbc, 0x38, 0xc1,
	0x1b, 0x58, 0x76, 0x53, 0xb5, 0x59, 0xda, 0x18, 0xee, 0xad, 0xd2, 0xe6, 0x98, 0xa6, 0x4b, 0xe4,
	0x18, 0x7a, 0x1f, 0xc2, 0xfc, 0xd9, 0x6a, 0xe4, 0x85, 0xa9, 0xf4, 0xbf, 0x8d, 0x3f, 0x41, 0xff,
	0xb4, 0x7e, 0x2a, 0xc9, 0xd3, 0x46, 0xe6, 0xbf, 0xcf, 0xed, 0xce, 0xde, 0x7d, 0xcb, 0x15, 0xdf,
	0x68, 0xc5, 0x3d, 0xdc, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x86, 0x81, 0x8c, 0x7a, 0xd4,
	0x07, 0x00, 0x00,
}
